[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "/.netlify/functions/api"

[functions]
  directory = "server/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
